### PR TITLE
Disable download chart buttons

### PR DESCRIPTION
**Pull request by ScottMG-PHS**
Adds optional argument to savechart_button() allowing button to be disabled - button will be grey with a popup to explain when pressed.

Trend and Rank save chart buttons are disabled

### CODE REVIEW

**Comment by ScottMG-PHS** [comment]
Wondering what you think about this approach @jvillacampa?

I could also include the coming soon save chart button on the summary page, and the commented out one on the inequalities page too? Although perhaps they are disabled for different reasons.

**Comment by jvillacampa** [comment]
Sorry it took me forever to get around to check this. It looks perfect, a shame is just to tell bad news to users!

**Comment by jvillacampa** [comment]
For the summary section - maybe add it there too. That viz was tricky to deal with even before the issues with Plotly. I think there are new approaches (packages that take screenshots of your app) that could work, but adding your solution makes more sense than the "coming soon" message.

 For inequalities maybe add it too. I think I was trying to provide some sort of reporting function to it, but that never ended happening

**Comment by ScottMG-PHS** [comment]
Thanks @jvillacampa, the inequalities and summary buttons are now disabled too (except the one for the spine plot, that seems to work).

Ready for review.

**Review by jvillacampa — APPROVED** [review]
Looks good to me, thanks for doing it!

**Pull request merged**
