### PR TITLE
Inequalities life ex

### PR DESCRIPTION
**Pull request by vaelliott**
So finally have changes ready to review for incorporating more inequalities indicators and smaller redesign of inequalities module. I think we may want to revisit the layout of inequalities module using an HTML layout so my changes are mostly around wording and explanatory text to text.
Changes to data prep script are required but I've written it so that it will pick up files from the data to be checked folder so these files aren't accidentally read in to the live app until we are ready to - this will need to be adjusted before the branch is merged into main.

### CODE REVIEW

**Comment by jvillacampa** [comment]
Hi Vicky, before I look at this, there are a few merge conflicts that might be good to solve first

**Comment by vaelliott** [comment]
Will do...sorry didn't spot that!

**Review by jvillacampa — COMMENTED** [review]
Hi Vicky,
thanks for this. It's a big improvement. Just some comments/suggestions, most of them can be ignored and just noted for future:

- Bar chart (patterns of inequality and potential for impact): Could this be vertical (invert axis), that way your labels would be horizontal
- You call it "potential for impact" but then use "potential for improvement" in the title. I think the latter is better.
- Summary text boxes at top: I like the (see xx section), a potential improvement is that that bit would be a link to each section. Not sure if that would be complicated
- Summary boxes: the first two bullet points need a dot at the end
- Filters in sidebar: They are very packed together, I think they need some white space between them and that would improve it.
- I would move legends to the top rather than at the bottom
- Legend for PAR: only includes the orange, probably should include both colours
- Confidence intervals for SII/RII: they are gigantic, which to a degree it makes them quite useless. The problem is that they are calculated on linear regressions on 5 points, so that's very little, particularly if the gradient is very steep (more variation in the data). I think using deciles would help, but maybe there is a smarter solution a statistician could come up with, maybe people at the MRC unit should be able to help?
- CIs are so large that I am guessing you are ignoring when saying gap has increased/decreased over time. As in most cases changes encompass so much that no statistically significant change can be appreciated (plus probably a time series analysis approach or SPC could be more appropiate for that).
- Patterns of inequality: titles very closed to summary text box, not the same in the rest of inequality views
- Data tab: this one doesn't include inequality data yet. 
- about these options?: Take out ? at end
- About these options - I would take the summary box when in this tab
- Save charts in about these options produces an error, perhaps you want to disable it there?
- Names like chart_3 and so on are not good ideas
- I feel the local/scotland quintiles might require some explanation somewhere. It might not be very clear for a large proportion of users.
- Immunisations trend chart is very difficult to read as all quintiles are grouped together, maybe a more dynamic y axis?
- Immunisations 6 in one Scotland message: "The most deprived areas have 1% the same vaccination uptake than Scotland as a whole. " I think something is failing there.
- Immunisations 6 in one NHS Ayrshire: "Over time absolute inequalities have decreased but relative inequalities have remained unchanged" However both of them follow the exact same trend. Also, CIs for this have some problem as they don't encompass the actual measure for some points.
- I checked the palette for the quintile gradient and it seems to meet accessibility criteria. Good contrast and color-blind safe.
- In indicators where more is better, tooltip of SII/RII charts show CIs the other way around.
- PAR: Bar chart tooltip shows figures without rounding for indicators when more is better.

**Comment by jvillacampa** [comment]
Looking forward to see it live, good job Vicky :)

**Comment by vaelliott** [comment]
closing as changes re-implemented in a new branch

**Pull request closed without merging**
